# Generated by Django 2.2.15 on 2020-10-24 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
