# Generated by Django 2.2.15 on 2020-10-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20201027_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=70),
        ),
    ]
